INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1001,'samsung','S100','active',NOW(),101);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1002,'samsung','S200','active',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1003,'LG','L100','inactive',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1004,'HITACHI','H100','active',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1005,'samsung','S900','inactive',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1006,'sony','SS100','active',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1007,'OGENERAL','O100','active',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1008,'Kirkland','K100','active',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1009,'Whirlpool','WP100','active',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1010,'Whirlpool','WP200','inactive',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1011,'Hoover','H200','active',NOW(),102);
INSERT INTO HOUSEHOLD(SERIALNUMBER,BRAND,MODEL,STATUS,DATEBOUGHT,USERID) VALUES(1012,'HP','HP200','active',NOW(),102);




