
DROP TABLE IF EXISTS HOUSEHOLD;

CREATE TABLE HOUSEHOLD(
SERIALNUMBER SERIAL PRIMARY KEY NOT NULL,
BRAND VARCHAR(20) NOT NULL,
MODEL VARCHAR(20) NOT NULL,
STATUS VARCHAR(20) NOT NULL,
DATEBOUGHT DATE NOT NULL,
);