INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('samsung','S100','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('samsung','S200','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('LG','L100','inactive',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('HITACHI','H100','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('samsung','S900','inactive',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('sony','SS100','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('OGENERAL','O100','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('Kirkland','K100','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('Whirlpool','WP100','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('Whirlpool','WP200','inactive',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('Hoover','H200','active',NOW());
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATEBOUGHT) VALUES('HP','HP200','active',NOW());




